# Generated by Django 4.2.2 on 2023-06-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
